wait_test.go: adjust margin on doBackoffTimeoutTest
when running on busy PC sometime we will fail on this scenario where we
don't meet expected timeout.

--- FAIL: TestBackoffTimeouts/delay:100ms;factor:1.0;lim:0s;retries:4 (0.31s)
    wait_test.go:112: BUG: retry 2 got delayed 111.658575ms instead of ~100ms

--- FAIL: TestBackoffTimeouts/delay:100ms;factor:1.0;lim:0s;retries:4 (0.32s)
    wait_test.go:112: BUG: retry 1 got delayed 112.315027ms instead of ~100ms

Increace margin to reduce false failures.

issue: LBM1-18109